import type { CreativeMetric, MetaSpikeCheck } from "./types";

export const funnels = [
  "All Offers",
  "Legacy Makers TV",
  "Women In Power TV",
  "Mompreneurs",
  "Operation CEO TV",
  "Kingdom Creators",
  "America's Best Builders TV",
  "America's Top Agents TV",
  "America's Best Doctors TV",
  "America's Top Contractors TV",
  "America's Top Authors TV",
  "Beyond Success TV",
  "Blue Collar America TV",
  "Creator Visionaries TV",
  "Inside Success TV",
  "Internet Masters TV",
  "Internet Millionaires",
  "Love Experts TV",
  "Made It In America",
  "Masters Of Innovation",
  "Unmapped / Review",
];

export const funnelMappings = [
  {
    keyword: "Legacy Makers",
    funnel: "Legacy Makers TV",
    owner: "Media buying",
    status: "Active",
    notes: "Matches current Legacy Makers casting campaign names.",
  },
  {
    keyword: "Women In Power",
    funnel: "Women In Power TV",
    owner: "Media buying",
    status: "Active",
    notes: "Confirmed historical winner exists for validation.",
  },
  {
    keyword: "Mompreneurs",
    funnel: "Mompreneurs",
    owner: "Media buying",
    status: "Active",
    notes: "Use exact keyword until naming convention is finalized.",
  },
  {
    keyword: "Operation CEO",
    funnel: "Operation CEO TV",
    owner: "Media buying",
    status: "Active",
    notes: "Needs sample loser confirmation during API spike.",
  },
  {
    keyword: "Kingdom Creators",
    funnel: "Kingdom Creators",
    owner: "Media buying",
    status: "Active",
    notes: "Hyros fallback only if campaign naming is inconsistent.",
  },
  {
    keyword: "Builders",
    funnel: "America's Best Builders TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Could match multiple builder-related naming variants.",
  },
  {
    keyword: "Top Agents",
    funnel: "America's Top Agents TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Best Doctors",
    funnel: "America's Best Doctors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Top Physicians",
    funnel: "America's Best Doctors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Physicians campaigns appear related to the doctors funnel; verify naming.",
  },
  {
    keyword: "Top Contractors",
    funnel: "America's Top Contractors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "America Contractors",
    funnel: "America's Top Contractors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed as a naming variant; verify preferred show name.",
  },
  {
    keyword: "Top Authors",
    funnel: "America's Top Authors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Americas Authors",
    funnel: "America's Top Authors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed as a campaign naming variant without the word Top.",
  },
  {
    keyword: "America's Authors",
    funnel: "America's Top Authors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed as a campaign naming variant without the word Top.",
  },
  {
    keyword: "Beyond Success",
    funnel: "Beyond Success TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "ABD FM",
    funnel: "America's Best Doctors TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed as an abbreviated Doctors naming variant.",
  },
  {
    keyword: "Blue Collar America",
    funnel: "Blue Collar America TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Creator Visionaries",
    funnel: "Creator Visionaries TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Inside Success",
    funnel: "Inside Success TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "General Inside Success casting campaigns should be reviewed separately.",
  },
  {
    keyword: "ISTV Shows",
    funnel: "Inside Success TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "General ISTV campaign naming observed during Phase 1 spike.",
  },
  {
    keyword: "Internet Masters",
    funnel: "Internet Masters TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Internet Millionaires",
    funnel: "Internet Millionaires",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Love Experts",
    funnel: "Love Experts TV",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Made It In America",
    funnel: "Made It In America",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
  {
    keyword: "Masters Of Innovation",
    funnel: "Masters Of Innovation",
    owner: "Media buying",
    status: "Needs review",
    notes: "Observed in live Meta campaign names during Phase 1 spike.",
  },
];

export const thresholdSettings = [
  {
    label: "Minimum spend",
    value: "$120",
    purpose: "Minimum signal before an ad is considered for any bucket.",
    locked: "Editable later through settings, hardcoded only for demo mode.",
  },
  {
    label: "Winner appointment threshold",
    value: "10+ appointments",
    purpose: "Minimum appointment volume required to rank as a Winner.",
    locked: "Configurable before production.",
  },
  {
    label: "Low-volume loser band",
    value: "1-2 appointments",
    purpose: "Flags meaningful spend with very low conversion volume.",
    locked: "Needs final sign-off after API spike.",
  },
  {
    label: "Target CPA benchmark",
    value: "$80",
    purpose: "Visual benchmark only, not a hard pass/fail filter.",
    locked: "Should become a per-funnel/account rolling reference later.",
  },
];

export const sampleCreatives: CreativeMetric[] = [
  {
    id: "ad_001",
    rank: 1,
    title: "Img | Casting | V5",
    format: "Image",
    version: "V5",
    previewText: "Your story deserves a bigger platform",
    funnel: "Legacy Makers TV",
    adAccount: "Inside Success TV",
    status: "Delivering",
    spend: 43658,
    leads: 1410,
    costPerLead: 10.94,
    appointments: 880,
    costPerAppointment: 48.93,
    bucket: "winning",
    attributionBasis: "appointment",
  },
  {
    id: "ad_002",
    rank: 2,
    title: "Video | Casting | V3",
    format: "Video",
    version: "V3",
    previewText: "Now casting powerful women in business",
    funnel: "Women In Power TV",
    adAccount: "Inside Success TV | Split Test",
    status: "Delivering",
    spend: 70141,
    leads: null,
    costPerLead: null,
    appointments: 1032,
    costPerAppointment: 67.97,
    bucket: "winning",
    attributionBasis: "appointment",
  },
  {
    id: "ad_003",
    rank: 3,
    title: "Img | Casting Call | V2",
    format: "Image",
    version: "V2",
    previewText: "Calling all mom bosses",
    funnel: "Mompreneurs",
    adAccount: "Inside Success TV",
    status: "Delivering",
    spend: 3204,
    leads: 18,
    costPerLead: 55.24,
    appointments: 45,
    costPerAppointment: 71.28,
    bucket: "winning",
    attributionBasis: "appointment",
  },
  {
    id: "ad_004",
    rank: 1,
    title: "Video | Casting | Zero Appts",
    format: "Video",
    version: "V1",
    previewText: "Are you the next Operation CEO?",
    funnel: "Operation CEO TV",
    adAccount: "Inside Success TV",
    status: "Delivering",
    spend: 820,
    leads: null,
    costPerLead: null,
    appointments: 0,
    costPerAppointment: null,
    bucket: "losing",
    attributionBasis: "appointment",
    loserTier: "zeroAppointments",
  },
  {
    id: "ad_005",
    rank: 2,
    title: "Img | Casting | High Cost",
    format: "Image",
    version: "V4",
    previewText: "Faith-driven founders now casting",
    funnel: "Kingdom Creators",
    adAccount: "Inside Success TV | Split Test",
    status: "Paused",
    spend: 1187,
    leads: 19,
    costPerLead: 62.47,
    appointments: 2,
    costPerAppointment: 593.5,
    bucket: "losing",
    attributionBasis: "appointment",
    loserTier: "lowVolumeHighCost",
  },
  {
    id: "ad_006",
    rank: 3,
    title: "Video | Builders | V2",
    format: "Video",
    version: "V2",
    previewText: "America's best builders wanted",
    funnel: "America's Best Builders TV",
    adAccount: "Inside Success TV",
    status: "Delivering",
    spend: 2840,
    leads: 44,
    costPerLead: 64.55,
    appointments: 8,
    costPerAppointment: 355,
    bucket: "notEnoughData",
    attributionBasis: "appointment",
  },
];

export const spikeChecklist: MetaSpikeCheck[] = [
  {
    name: "Ad account access",
    status: "not_started",
    detail: "Confirm the temporary token or system-user token can read both approved ad accounts.",
  },
  {
    name: "Campaign objective filtering",
    status: "not_started",
    detail: "Confirm Leads / appointment-scheduled campaigns can be filtered before storage.",
  },
  {
    name: "Insights metrics",
    status: "not_started",
    detail: "Pull spend, leads if available, appointments, CPA/CPL source fields, and status.",
  },
  {
    name: "Creative previews",
    status: "not_started",
    detail: "Pull image_url / thumbnail_url or viable fallback from AdCreative.",
  },
  {
    name: "Preview URL durability",
    status: "not_started",
    detail: "Check whether preview URLs render outside ad-account context and how long they persist.",
  },
  {
    name: "Funnel mapping",
    status: "not_started",
    detail: "Test campaign-name keyword lookup; log unmatched/ambiguous campaigns.",
  },
  {
    name: "Hyros need",
    status: "not_started",
    detail: "Decide if Hyros fallback is required after Meta naming test.",
  },
  {
    name: "Sync cadence",
    status: "not_started",
    detail: "Estimate safe cadence from rate limits, data volume, and response times.",
  },
];
